### ISSUE TITLE
Calling `client.heart_rate_intraday_time_series` returns results 'Get Heart Rate Time Series'

### ISSUE THREAD

**Issue by brycemcd** [kaorumori/fitbit-api-ruby-client#3]
When I am using this gem and execute the following code, I expect results from the [Intraday API endpoint](https://dev.fitbit.com/docs/heart-rate/#get-heart-rate-intraday-time-series). Instead, I'm getting results from the [Heart Rate Time Series](https://dev.fitbit.com/docs/heart-rate/#get-heart-rate-time-series)

```ruby
date = '2016-11-25' # example date, but doesn't matter 
 client.heart_rate_intraday_time_series(
      user_id: '-',
      date: date,
      start_time: '00:00',
      end_date: '23:59',
      detail_level: '1sec'
    )
```

You can see how we're using this gem in [this pull request](https://github.com/brycemcd/heart-rate-calendar/pull/2)

**Comment by wvance** [comment]
Is your app type set to 'Personal' through the fitbit API, or has Fitbit given you permission to use the intraday endpoint?

**Comment by kaorumori** [comment]
That's right.
Your app should be 'Personal' or granted access from Fitbit.
