### ISSUE TITLE
refresh_token not returned in order to be saved back to "user"

### ISSUE THREAD

**Issue by tomkadwill** [kaorumori/fitbit-api-ruby-client#4]
Hi there,

When a user's token expires I can see that the gem will refresh the token: https://github.com/kaorumori/fitbit-api-ruby-client/blob/34cdd132889c8893c54426e615c797d2b9d3bc15/lib/fitbit/client.rb#L46-L47

The problem is that the new `access_token` and `refresh_token` are not returned so I cannot assign the new values to the `User` object.

This means that, if I make a request for a user who's tokens have expired, it will work the first time but fail for subsequent calls because the `access_token` and `refresh_token` stored on the patient are invalid.

Is this a bug or am I missing something? If this is a bug, I'm happy to help contribute a fix.

**Comment by mattvanhorn** [comment]
I'm also willing to help on this. I've just been reauthorizing, for now.

**Comment by mattvanhorn** [comment]
It looks like the refresh! method returns all you would need. I think the easy solution would just be to check your own expire time and manually refresh if you need to. Then you could take the returned access token, and get the token, refresh_token, and expires_at from that.
Maybe I'm missing something? I think I'm not having this same issue, because my Fitbit Omniauth strategy is updating the record, as opposed to relying just on this client.

**Comment by tomkadwill** [comment]
Hi @mattvanhorn, thanks for looking into this!

`refresh!` does return everything that you would need but the problem is that `refresh!` is called by other methods inside the gem (eg: https://github.com/kaorumori/fitbit-api-ruby-client/blob/34cdd132889c8893c54426e615c797d2b9d3bc15/lib/fitbit/client.rb#L46-L47) and the return value is lost.

I also think that the gem should handle token refreshing because otherwise the user will need to check the token each time and manually refresh it (if required). Alternatively, methods like `get` and `post` should fail and return an error to the user, if the token has expired.

**Comment by kaorumori** [comment]
I added attr_accessor of access_token. access_token is an instance of OAuth2::AccessToken. You can get updated token by using access_token.

```ruby
client.access_token.token
client.access_token.refresh_token
client.access_token.expires_at
```

For this change, one of keyword arguments that initializing client "access_token" is renamed to "token".

```ruby
client = Fitbit::Client.new(
  client_id: Settings.fitbit.client_id,
  client_secret: Settings.fitbit.client_secret,
  token: current_user.token,
  refresh_token: current_user.refresh_token,
  expires_at: current_user.expires_at)
```

It is supported from version 0.1.0.

**Comment by tomkadwill** [comment]
@kaorumori that's nice!

Ideally there would be some way to know whether `client` needed to refresh the token. Because it's only when the token was refreshed that you need to save it back to the user record.

I guess you could still make it work with this new attr_accessor, you could save `client.access_token.token`, `client.access_token.refresh_token` & `client.access_token.expires_at` back to the user object each time. It's just not very efficient because most of the time these values don't change

**Comment by kaorumori** [comment]
Thank you, @tomkadwill 

We can know whether access_token is expired or not and refresh explicitly. This is sample code that update user object if token is expired.

```ruby
if client.access_token.expired?
  client.refresh!
  user.update(token: client.access_token.token.
                       refresh_token: client.access_token.refresh_token
                       expires_at: client.access_token.expires_at)
end
```

**Comment by tomkadwill** [comment]
Cool! Looks good 👍 

And would it make sense to remove the `self.refresh!` from `get`, `post` and `delete`? Eg, https://github.com/kaorumori/fitbit-api-ruby-client/blob/34cdd132889c8893c54426e615c797d2b9d3bc15/lib/fitbit/client.rb#L46-L47

Because, if those methods are called directly, it will result in the new token and refresh_token getting lost AFAIK.

**Comment by kaorumori** [comment]
That's good idea.
I removed `self.refresh!` from `get`, `post` and `delete`.
It is supported from version 0.1.1.

**Comment by tomkadwill** [comment]
Thanks @kaorumori! Nice work 👍
