### ISSUE TITLE
Needs license information

### ISSUE THREAD

**Issue by mattvanhorn** [kaorumori/fitbit-api-ruby-client#5]
I'd like to make sure I can use this in my project legally - providing a license would make it easy for people to know.

MIT license is here: http://choosealicense.com/licenses/mit/ and I am willing to make the PR if this license is acceptable.

**Comment by kaorumori** [comment]
This project's license is Apache-2.0.
https://rubygems.org/gems/fitbit-api-client/

I forgot to add LICENSE.txt.
LICENSE.txt will be added for next release.
