### ISSUE TITLE
Returning error objects instead of raising them makes error handling clumsy.

### ISSUE THREAD

**Issue by mattvanhorn** [kaorumori/fitbit-api-ruby-client#6]
Everywhere I use this client, I need an if/else statement to catch errors, like this:
```ruby
    raw_data = fitbit_client.some_method
    if raw_data.is_a? OAuth2::Error
      # handle error
    else
      # use data
    end
```
I think it would be nicer if I could do this instead:
```ruby
    begin
      raw_data = fitbit_client.some_method
      # use data
    rescue OAuth2::Error => e
      # handle error
    end
```
Then I get more options for how to deal with the error, such as wrapping it or reraising it, or retrying request. 

Is there a reason you wanted to return the error object rather than just raising it? Is there another way to tell if my request succeeded, so I can call Hash methods on it?

**Comment by kaorumori** [comment]
@mattvanhorn Thank you.

I've changed `Fitbit::Client`'s methods (get, post and delete) not to return error object.
https://github.com/kaorumori/fitbit-api-ruby-client/blob/eb9297cdd5504353b1b9043ae38e31a72d75a1f1/lib/fitbit/client.rb#L40-L41
It is
(version 0.1.2) 

I think it can raise exceptions, but I'm not sure this is correct or not.

**Comment by mattvanhorn** [comment]
That looks like it should work. I'm going to upgrade to this version on my acceptance env, and test it out a bit.
