### ISSUE TITLE
activity_tcx method is returning JSON::ParserError

### ISSUE THREAD

**Issue by ikbenben** [kaorumori/fitbit-api-ruby-client#8]
After creating a client, trying to invoke the activity_tcx method on the client returns a JSON parse error as the result is being returned as XML. As per the documentation at https://dev.fitbit.com/docs/activity/#get-activity-tcx, the result is a TCX file which is an XML format

```
irb(main):019:0> fitbit_client.activity_tcx(log_id: 7087212355)
=> #<JSON::ParserError: 757: unexpected token at '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TrainingCenterDatabase xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2">
    <Activities>
        <Activity Sport="Other">

```

**Comment by kaorumori** [comment]
JSON.parse() is failed because https://api.fitbit.com/1/user/[user-id]/activities/[log-id].tcx returns XML.
I've changed fitbit_client returns plain text when JSON.parse() is failed.
