### ISSUE TITLE
activity_logs_list is return error due to missing parameters

### ISSUE THREAD

**Issue by ikbenben** [kaorumori/fitbit-api-ruby-client#9]
When calling the activity_logs_list method, the associated end point expects a beforeDate or afterDate parameter however the code does not seem to allow this to be supplied so the method results in an error

```
fitbit_client.activity_logs_list
=> #<OAuth2::Error: : 
{"errors":[{"errorType":"validation","fieldName":"date","message":"beforeDate or afterDate is required"}]}>
```

**Comment by kaorumori** [comment]
Thank you.
I added some parameters to activity_logs_list() method.
